# Setup
title:               Candlelit Ramblings
tagline:             'The best kind of ramblings'
description:         'Technical essays and tidbits from the world of simulation and optimization.'
url:                 http://jamesneb.github.io
baseurl:             ''   
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              James Nebeker
  url:               https://jamesneb.github.io
  email:             jnebeker@truckitapp.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

  #Build Settings
markdown: kramdown
remote_theme: poole/lanyon.git
